"""
Microstrip Patch Antenna Calculator — FastAPI Application

Main entrypoint for the backend API.
Swagger docs available at /docs (auto-generated by FastAPI).
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.v1.patch_antenna import router as patch_antenna_router

app = FastAPI(
    title="Microstrip Patch Antenna Calculator API",
    description=(
        "Calculate the physical dimensions (Width & Length) of a rectangular "
        "microstrip patch antenna using the Transmission Line Model "
        "(Balanis, 4th Ed., Chapter 14). Supports basic and advanced mode "
        "calculations with model validity warnings."
    ),
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# CORS — allow frontend dev server and any deployed frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register routers
app.include_router(patch_antenna_router)


@app.get("/", include_in_schema=False)
async def root():
    """Redirect root to API docs."""
    return {
        "message": "Microstrip Patch Antenna Calculator API",
        "docs": "/docs",
        "health": "/api/v1/patch-antenna/health",
    }
